name: CI

on:
  push:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Cache CLI tools managed by SwiftPM
        uses: actions/cache@v2
        id: tools-cache
        with:
          path: Tools/.build
          key: ${{ runner.os }}-spm-tools-${{ hashFiles('**/Tools/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-tools-
      - name: Build CLI tools managed by SwiftPM
        if: steps.tools-cache.outputs.cache-hit != 'true'
        run: make build-tools
      - name: Cache libraries managed by SwiftPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: make build
